/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as verifiers from "./Verifiers";
export type { verifiers };
import type * as zkOtpValidatorSol from "./ZkOtpValidator.sol";
export type { zkOtpValidatorSol };
export type { ZkSocialRecoveryWallet } from "./ZkSocialRecoveryWallet";
