/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IOtpMerkleTreeVerifier } from "./IOtpMerkleTreeVerifier";
export type { ZkOtpValidator } from "./ZkOtpValidator";
