/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IOtpMerkleTreeVerifier,
  IOtpMerkleTreeVerifierInterface,
} from "../../../contracts/ZkOtpValidator.sol/IOtpMerkleTreeVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "a",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "b",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "c",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2]",
        name: "input",
        type: "uint256[2]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IOtpMerkleTreeVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IOtpMerkleTreeVerifierInterface {
    return new utils.Interface(_abi) as IOtpMerkleTreeVerifierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOtpMerkleTreeVerifier {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IOtpMerkleTreeVerifier;
  }
}
