/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "Verifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier__factory>;
    getContractFactory(
      name: "OtpMerkleTreeVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OtpMerkleTreeVerifier__factory>;
    getContractFactory(
      name: "IOtpMerkleTreeVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IOtpMerkleTreeVerifier__factory>;
    getContractFactory(
      name: "ZkOtpValidator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZkOtpValidator__factory>;
    getContractFactory(
      name: "ZkSocialRecoveryWallet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZkSocialRecoveryWallet__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "Verifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier>;
    getContractAt(
      name: "OtpMerkleTreeVerifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OtpMerkleTreeVerifier>;
    getContractAt(
      name: "IOtpMerkleTreeVerifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IOtpMerkleTreeVerifier>;
    getContractAt(
      name: "ZkOtpValidator",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ZkOtpValidator>;
    getContractAt(
      name: "ZkSocialRecoveryWallet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ZkSocialRecoveryWallet>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
